input_data = open('input.txt' , 'r')
data = input_data.read()
data = data.split()
a1 = int(data[0])
a2 = int(data[1])
a3 = int(data[2])
s = int(a1 * ( 1 - a2 ** a3 ) / ( a2 - 1 ))
output_data = open('output.txt','a')
output_data.write(str(s))
input_data.close()
output_data.close()